#!/usr/bin/env python3
"""
TouchLab Sampler Router Generator — v2 (r/s fix)
=================================================

Generates sampler-router.pd — the central patch that routes audio input
sources (ch1..chN + master) to M sampler slots, and dispatches per-slot
autotrim threshold/preroll values from global FUDI commands.

FIX (v2 vs v1):
    The previous version used [value slotN-src-idx] as the per-slot
    source-index store. In vanilla Pd, [value] stores a float on its
    inlet but does NOT fire its outlet — the outlet only fires on a bang.
    Consequence: downstream [== N] gates never re-evaluated, all *~ gates
    stayed at 0, and every sampler slot recorded silence regardless of
    loadbang defaults or FUDI routing commands.

    The fix replaces the [value] store with an [r slotN-src-idx] reader
    (which fires its outlet whenever any [s slotN-src-idx] sends a value)
    and routes all writers — loadbang default + FUDI per-source — through
    [s slotN-src-idx] send objects. External interface is unchanged:
    FUDI `sampler-router-input <slot> <source>` commands work as before,
    and the `send~ slotN-src-sig` outputs still feed sampler-slot-N.pd.

Usage:
    python3 generate-router.py [--channels N] [--slots M]

Reads session.json for defaults, with CLI overrides.
"""

from pathlib import Path
import argparse
import json
import sys

HERE = Path(__file__).parent.resolve()
SESSION_JSON = HERE / "session.json"


class PdBuilder:
    """Builds a .pd file; buffers connections to emit at end (PD syntax)."""
    def __init__(self):
        self.lines = []
        self.connections = []
        self.n = 0
    def canvas(self, x, y, w, h, fs):
        self.lines.append(f"#N canvas {x} {y} {w} {h} {fs};")
    def text(self, x, y, content):
        self.lines.append(f"#X text {x} {y} {content};")
        i = self.n; self.n += 1; return i
    def obj(self, x, y, content):
        self.lines.append(f"#X obj {x} {y} {content};")
        i = self.n; self.n += 1; return i
    def msg(self, x, y, content):
        self.lines.append(f"#X msg {x} {y} {content};")
        i = self.n; self.n += 1; return i
    def connect(self, s, so, d, di):
        self.connections.append(f"#X connect {s} {so} {d} {di};")
    def render(self):
        return "\n".join(self.lines + self.connections) + "\n"


def build_router(num_channels, num_slots):
    pd = PdBuilder()
    pd.canvas(40, 40, 1600, 1200, 10)

    pd.text(10, 8,
            f"TouchLab Sampler Router — {num_channels} ch + master -> {num_slots} slots")
    pd.text(10, 26,
            "GENERATED by generate-router.py (edits will be overwritten)")

    # Input source receives
    pd.text(10, 60, "Input taps from mixer:")
    src_receives = []
    for c in range(1, num_channels + 1):
        r = pd.obj(10 + (c - 1) * 120, 85, f"receive~ sampler-src-ch{c}")
        src_receives.append(r)
    master_r = pd.obj(10 + num_channels * 120, 85, "receive~ sampler-src-master")

    sources = src_receives + [master_r]
    source_names = [f"ch{c}" for c in range(1, num_channels + 1)] + ["master"]

    # Per-slot: [r slotN-src-idx] reader feeds every gate. Writers elsewhere
    # all use [s slotN-src-idx] so every update to the idx fires the gates.
    pd.text(10, 140,
            "Per-slot input selectors (r/s bus + gate+sum — [value] replaced to fix non-firing outlet)")
    slot_x_step = 450
    slot_y_base = 170

    for k in range(1, num_slots + 1):
        x = 10 + (k - 1) * slot_x_step
        y = slot_y_base

        # Reader: fires its outlet on every incoming float
        idx_source = pd.obj(x, y, f"r slot{k}-src-idx")

        # For each source, a gate:
        #   [idx_source] → [== i] → [pack 0 20] → [line~] → *~ (right inlet)
        # *~ outputs either silence or the source signal; all summed into send~.
        gate_outs = []
        for i, src in enumerate(sources):
            gx = x + i * 85
            gy = y + 40
            eq  = pd.obj(gx, gy,      f"== {i}")
            pk  = pd.obj(gx, gy + 25, "pack 0 20")
            ln  = pd.obj(gx, gy + 50, "line~")
            mul = pd.obj(gx, gy + 80, "*~")
            pd.connect(idx_source, 0, eq, 0)
            pd.connect(eq, 0, pk, 0)
            pd.connect(pk, 0, ln, 0)
            pd.connect(ln, 0, mul, 1)
            pd.connect(src, 0, mul, 0)
            gate_outs.append(mul)

        # Sum all gate outputs via +~ chain
        if len(gate_outs) == 1:
            sum_out = gate_outs[0]
        else:
            prev = pd.obj(x, y + 260, "+~")
            pd.connect(gate_outs[0], 0, prev, 0)
            pd.connect(gate_outs[1], 0, prev, 1)
            for j in range(2, len(gate_outs)):
                nxt = pd.obj(x, y + 260 + (j - 1) * 25, "+~")
                pd.connect(prev, 0, nxt, 0)
                pd.connect(gate_outs[j], 0, nxt, 1)
                prev = nxt
            sum_out = prev

        out = pd.obj(x, y + 260 + max(1, len(gate_outs) - 1) * 25 + 30,
                     f"send~ slot{k}-src-sig")
        pd.connect(sum_out, 0, out, 0)

    # Loadbang defaults — all slots route to idx 0 (= ch1)
    # Each slot has its own [s slotN-src-idx] fed from the same msg 0.
    pd.text(10, 590, "Loadbang defaults (all slots -> ch1 = idx 0):")
    lb     = pd.obj(10, 615, "loadbang")
    lb_msg = pd.msg(10, 640, "0")
    pd.connect(lb, 0, lb_msg, 0)
    for k in range(1, num_slots + 1):
        s_lb = pd.obj(10 + (k - 1) * 150, 670, f"s slot{k}-src-idx")
        pd.connect(lb_msg, 0, s_lb, 0)

    # Input command dispatch
    pd.text(10, 710, "FUDI control: sampler-router-input <slot> <source>")
    cmd_recv  = pd.obj(10, 735, "r sampler-router-input")
    cmd_route = pd.obj(
        10, 765,
        "route " + " ".join(str(k) for k in range(1, num_slots + 1))
    )
    pd.connect(cmd_recv, 0, cmd_route, 0)

    y = 810
    for k in range(1, num_slots + 1):
        x = 10 + (k - 1) * slot_x_step

        sym_route = pd.obj(x, y, "route " + " ".join(source_names))
        pd.connect(cmd_route, k - 1, sym_route, 0)

        for idx, name in enumerate(source_names):
            const = pd.obj(x + idx * 70, y + 40, f"f {idx}")
            pd.connect(sym_route, idx, const, 0)

            # Write via send; the slot's r slot{k}-src-idx reader will fire gates.
            s_fudi = pd.obj(x + idx * 70, y + 70, f"s slot{k}-src-idx")
            pd.connect(const, 0, s_fudi, 0)

            # Status broadcast (shifted down to make room for s_fudi)
            st_list = pd.obj(x + idx * 70, y + 110,
                             f"list prepend sampler-status {k} input {name}")
            st_send = pd.obj(x + idx * 70, y + 140, "s sampler-status-out")
            pd.connect(sym_route, idx, st_list, 0)
            pd.connect(st_list, 0, st_send, 0)

    # Autotrim threshold dispatcher (shifted down because FUDI section grew)
    pd.text(10, 1000, "Autotrim threshold dispatcher:")
    at_recv  = pd.obj(10, 1025, "r sampler-autotrim-threshold")
    at_route = pd.obj(10, 1050,
                      "route " + " ".join(str(k) for k in range(1, num_slots + 1)))
    pd.connect(at_recv, 0, at_route, 0)
    for k in range(1, num_slots + 1):
        s = pd.obj(10 + (k - 1) * 150, 1080, f"s slot{k}-autotrim-threshold-db")
        pd.connect(at_route, k - 1, s, 0)

    # Autotrim preroll dispatcher
    pd.text(10, 1120, "Autotrim preroll dispatcher:")
    ap_recv  = pd.obj(10, 1145, "r sampler-autotrim-preroll")
    ap_route = pd.obj(10, 1170,
                      "route " + " ".join(str(k) for k in range(1, num_slots + 1)))
    pd.connect(ap_recv, 0, ap_route, 0)
    for k in range(1, num_slots + 1):
        s = pd.obj(10 + (k - 1) * 150, 1200, f"s slot{k}-autotrim-preroll-ms")
        pd.connect(ap_route, k - 1, s, 0)

    return pd.render()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--channels", type=int, default=None)
    ap.add_argument("--slots", type=int, default=None)
    ap.add_argument("--output", type=str, default="sampler-router.pd")
    args = ap.parse_args()

    n_ch, n_sl = args.channels, args.slots
    if n_ch is None or n_sl is None:
        if not SESSION_JSON.exists():
            print("ERROR: session.json not found and no CLI overrides given.")
            sys.exit(1)
        cfg = json.loads(SESSION_JSON.read_text())
        if n_ch is None: n_ch = len(cfg.get("channels", []))
        if n_sl is None: n_sl = cfg.get("sampler", {}).get("slots", 8)

    if not (1 <= n_ch <= 32):
        print(f"ERROR: channels must be 1..32, got {n_ch}"); sys.exit(1)
    if not (1 <= n_sl <= 16):
        print(f"ERROR: slots must be 1..16, got {n_sl}"); sys.exit(1)

    out = HERE / args.output
    content = build_router(n_ch, n_sl)
    out.write_text(content)
    print(f"Built router: {out.name} ({content.count(chr(10))} lines, "
          f"{n_ch} channels + master -> {n_sl} slots)")


if __name__ == "__main__":
    main()
