#!/usr/bin/env python3
"""
TouchLab Sampler - Slot generator
=================================

Reads sampler-slot-1.pd as the canonical template and generates
sampler-slot-2.pd ... sampler-slot-N.pd by string substitution.
Also regenerates sampler-host.pd with N slot abstractions and
debug prints.

Usage:
    python3 generate-slots.py          # 8 slots (default)
    python3 generate-slots.py 4        # 4 slots
"""

from pathlib import Path
import re
import sys

HERE = Path(__file__).parent.resolve()
TEMPLATE = HERE / "sampler-slot-1.pd"
HOST = HERE / "sampler-host.pd"
DEFAULT_NUM_SLOTS = 8


# --------------------------------------------------------------------------
# Slot file generation
# --------------------------------------------------------------------------

def generate_slot(n):
    """Write sampler-slot-{n}.pd based on the slot-1 template."""
    src = TEMPLATE.read_text()

    # slot1 → slotN (internal sends/receives, array name, file paths)
    # \b ensures we don't match slot10, slot11 etc.
    src = re.sub(r'\bslot1\b', f'slot{n}', src)

    # route 1 → route N (command dispatch filter)
    src = re.sub(r'\broute 1\b', f'route {n}', src)

    # [f 1] objects that initialize the slot number in status messages.
    # These match a very specific pattern: "#X obj X Y f 1;" — the init
    # value is a literal 1 that must become N.  We match the full line
    # so we do not accidentally rewrite other "f 1" fragments.
    src = re.sub(
        r'^(#X obj \d+ \d+ f )1;$',
        rf'\g<1>{n};',
        src,
        flags=re.MULTILINE,
    )

    # Update the header comment for clarity
    src = re.sub(
        r'TouchLab Sampler Slot 1',
        f'TouchLab Sampler Slot {n}',
        src
    )

    out = HERE / f"sampler-slot-{n}.pd"
    out.write_text(src)
    return out


# --------------------------------------------------------------------------
# Host file generation
# --------------------------------------------------------------------------

class PdBuilder:
    """Tiny helper to build a .pd file while tracking object indices.
    Connections are buffered and emitted at the end (required by PD)."""

    def __init__(self):
        self.lines = []
        self.connections = []
        self.obj_count = 0

    def canvas(self, x, y, w, h, font_size):
        self.lines.append(f"#N canvas {x} {y} {w} {h} {font_size};")

    def text(self, x, y, content):
        self.lines.append(f"#X text {x} {y} {content};")
        idx = self.obj_count
        self.obj_count += 1
        return idx

    def obj(self, x, y, content):
        self.lines.append(f"#X obj {x} {y} {content};")
        idx = self.obj_count
        self.obj_count += 1
        return idx

    def msg(self, x, y, content):
        self.lines.append(f"#X msg {x} {y} {content};")
        idx = self.obj_count
        self.obj_count += 1
        return idx

    def connect(self, src_idx, src_out, dst_idx, dst_in):
        self.connections.append(
            f"#X connect {src_idx} {src_out} {dst_idx} {dst_in};"
        )

    def render(self):
        return "\n".join(self.lines + self.connections) + "\n"


def build_host(num_slots, num_channels=4, test_mode=True):
    """Build sampler-host.pd from scratch.

    Args:
        num_slots: number of sampler slots
        num_channels: how many channels the router expects (determines the
            mock source taps when test_mode=True)
        test_mode: if True, emit [adc~ N] → [throw~ sampler-src-chN] taps
            so the router sees real audio when running the host standalone.
            Set to False when integrating into touchlab-mixer.pd (the
            mixer will emit its own source taps).
    """
    pd = PdBuilder()
    pd.canvas(60, 60, 1600, 1000, 10)

    pd.text(20, 10,
            f"TouchLab Sampler HOST - v2 - {num_slots} slots, "
            f"{num_channels} ch {'(test mode)' if test_mode else ''}")
    pd.text(20, 28,
            "GENERATED by generate-slots.py (edits will be overwritten)")

    # ------------------------------------------------------------------
    # FUDI input chain
    # ------------------------------------------------------------------
    nr = pd.obj(20, 80, "netreceive -u -b 9002")
    fp = pd.obj(20, 110, "fudiparse")
    pr_raw = pd.obj(280, 110, "print fudi-raw")

    rt = pd.obj(20, 150,
                "route sampler-load sampler-play sampler-stop "
                "sampler-vol sampler-speed sampler-rec-start "
                "sampler-rec-stop sampler-trim sampler-trim-end "
                "sampler-autotrim sampler-autotrim-threshold "
                "sampler-autotrim-preroll sampler-router-input "
                "sampler-master-vol")

    # 14 route outlets → 14 sends (+ unknown-fudi catch-all)
    send_specs = [
        (20,  190, "s sampler-load"),
        (140, 190, "s sampler-play"),
        (260, 190, "s sampler-stop"),
        (380, 190, "s sampler-vol"),
        (500, 190, "s sampler-speed"),
        (620, 190, "s sampler-rec-start"),
        (780, 190, "s sampler-rec-stop"),
        (20,  220, "s sampler-trim"),
        (160, 220, "s sampler-trim-end"),
        (320, 220, "s sampler-autotrim"),
        (500, 220, "s sampler-autotrim-threshold"),
        (760, 220, "s sampler-autotrim-preroll"),
        (20,  250, "s sampler-router-input"),
        (200, 250, "s sampler-master-vol"),
    ]
    send_idxs = [pd.obj(x, y, c) for (x, y, c) in send_specs]

    pr_unk = pd.obj(20, 290, "print unknown-fudi")

    # ------------------------------------------------------------------
    # Status return path
    # ------------------------------------------------------------------
    r_stat = pd.obj(20, 340, "r sampler-status-out")
    ns = pd.obj(20, 365, "netsend 1")

    # ------------------------------------------------------------------
    # Loadbang: connect to 9003 and enable DSP
    # ------------------------------------------------------------------
    lb = pd.obj(20, 420, "loadbang")
    tbb = pd.obj(20, 445, "t b b")
    m_connect = pd.msg(20, 480, "connect 127.0.0.1 9003")
    m_dsp = pd.msg(180, 480, r"\; pd dsp 1")

    # ------------------------------------------------------------------
    # Master-vol initialisatie:
    # Bridge stuurt 'sampler-master-vol <0..1>'. Het [s sampler-master-vol]
    # in de FUDI-route bovenin geeft dat door aan elke slot's eigen
    # [r sampler-master-vol] -> [line~] -> *~. Hier alleen een loadbang
    # die 1.0 stuurt zodat slots bij Pd-startup vol open staan.
    # ------------------------------------------------------------------
    mv_lb     = pd.obj(20, 540, "loadbang")
    mv_init   = pd.msg(20, 565, "1")
    mv_init_s = pd.obj(20, 590, "s sampler-master-vol")
    pd.connect(mv_lb, 0, mv_init, 0)
    pd.connect(mv_init, 0, mv_init_s, 0)

    # ------------------------------------------------------------------
    # Sampler router abstraction
    # ------------------------------------------------------------------
    router = pd.obj(900, 80, "sampler-router")

    # ------------------------------------------------------------------
    # Slot abstractions (2 columns of up to 4 rows)
    # ------------------------------------------------------------------
    slot_idxs = []
    for i in range(num_slots):
        col = i // 4
        row = i % 4
        x = 1100 + col * 220
        y = 80 + row * 60
        slot_idxs.append(pd.obj(x, y, f"sampler-slot-{i + 1}"))

    # ------------------------------------------------------------------
    # Test mode: tap adc~ into sampler-src-chN
    # In production (touchlab-mixer.pd) these come from [catch~ chN]
    # inside the mixer's channel patches.
    # ------------------------------------------------------------------
    if test_mode:
        pd.text(900, 140, "Test-mode source taps (adc~ N -> sampler-src-chN):")
        for c in range(1, num_channels + 1):
            x_t = 900 + (c - 1) * 130
            adc = pd.obj(x_t, 170, f"adc~ {c}")
            thr = pd.obj(x_t, 195, f"send~ sampler-src-ch{c}")
            pd.connect(adc, 0, thr, 0)
        # Master mock: just ch1 again for test
        adc_m = pd.obj(900 + num_channels * 130, 170, "adc~ 1")
        thr_m = pd.obj(900 + num_channels * 130, 195, "send~ sampler-src-master")
        pd.connect(adc_m, 0, thr_m, 0)

    # ------------------------------------------------------------------
    # Global debug prints (one per command, shows slot arg)
    # ------------------------------------------------------------------
    # ------------------------------------------------------------------
    debug_defs = [
        ("sampler-load",               "load-recv"),
        ("sampler-play",               "play-recv"),
        ("sampler-stop",               "stop-recv"),
        ("sampler-vol",                "vol-recv"),
        ("sampler-speed",              "speed-recv"),
        ("sampler-rec-start",          "rec-start-recv"),
        ("sampler-rec-stop",           "rec-stop-recv"),
        ("sampler-trim",               "trim-recv"),
        ("sampler-trim-end",           "trim-end-recv"),
        ("sampler-autotrim",           "autotrim-recv"),
        ("sampler-autotrim-threshold", "autotrim-threshold-recv"),
        ("sampler-autotrim-preroll",   "autotrim-preroll-recv"),
        ("sampler-router-input",       "router-input-recv"),
    ]
    debug_pairs = []
    y_debug = 520
    for i, (recv_name, print_label) in enumerate(debug_defs):
        col = i // 4
        row = i % 4
        x = 20 + col * 220
        y = y_debug + row * 60
        r_idx = pd.obj(x, y, f"r {recv_name}")
        p_idx = pd.obj(x, y + 25, f"print {print_label}")
        debug_pairs.append((r_idx, p_idx))

    # ------------------------------------------------------------------
    # Connections
    # ------------------------------------------------------------------
    pd.connect(nr, 0, fp, 0)            # netreceive → fudiparse
    pd.connect(fp, 0, rt, 0)            # fudiparse → route
    pd.connect(fp, 0, pr_raw, 0)        # fudiparse → print fudi-raw

    # route: 12 matched outlets → 12 sends, last outlet → unknown-fudi
    for i, s in enumerate(send_idxs):
        pd.connect(rt, i, s, 0)
    pd.connect(rt, len(send_idxs), pr_unk, 0)

    # Status return + loadbang chain
    pd.connect(r_stat, 0, ns, 0)
    pd.connect(lb, 0, tbb, 0)
    pd.connect(tbb, 0, m_connect, 0)   # tbb outlet 0 (fires last) → connect
    pd.connect(tbb, 1, m_dsp, 0)       # tbb outlet 1 (fires first) → dsp
    pd.connect(m_connect, 0, ns, 0)    # connect msg → netsend left inlet

    # Debug prints
    for r_idx, p_idx in debug_pairs:
        pd.connect(r_idx, 0, p_idx, 0)

    return pd.render()


# --------------------------------------------------------------------------
# Main
# --------------------------------------------------------------------------

def main():
    import json
    n = DEFAULT_NUM_SLOTS
    num_channels = 4

    # Read defaults from session.json if available
    sess = HERE / "session.json"
    if sess.exists():
        try:
            cfg = json.loads(sess.read_text())
            num_channels = len(cfg.get("channels", [])) or num_channels
            n = cfg.get("sampler", {}).get("slots", n)
        except Exception:
            pass

    if len(sys.argv) > 1:
        try:
            n = int(sys.argv[1])
            if n < 1 or n > 32:
                raise ValueError
        except ValueError:
            print(f"Usage: {sys.argv[0]} [num_slots]  (1-32, default {DEFAULT_NUM_SLOTS})")
            sys.exit(1)

    if not TEMPLATE.exists():
        print(f"ERROR: template not found: {TEMPLATE}")
        sys.exit(1)

    tpl_lines = TEMPLATE.read_text().count("\n")
    print(f"Template: {TEMPLATE.name} ({tpl_lines} lines)")
    print(f"Config:   {num_channels} channels, {n} slots")

    print(f"\nGenerating slots 2..{n}:")
    for slot in range(2, n + 1):
        out = generate_slot(slot)
        out_lines = out.read_text().count("\n")
        print(f"  wrote {out.name} ({out_lines} lines)")

    print(f"\nBuilding host file for {n} slots (test mode, {num_channels} channels):")
    host_content = build_host(n, num_channels=num_channels, test_mode=True)
    HOST.write_text(host_content)
    print(f"  wrote {HOST.name} ({host_content.count(chr(10))} lines)")

    print("\nDone.")


if __name__ == "__main__":
    main()
